name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: setup git auth
        run: |
          git config --global user.name "AdaiasMagdiel"
          git config --global user.email "adaiasmagdiell@gmail.com"
      - name: deploy to gh-pages
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i
          NODE_ENV=production npm run build
          cd dist
          git init
          git add -A
          git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
          git push -f "https://github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
